### ISSUE TITLE
[README] Add tested OS distribution and how to run vanilla Erlang

### ISSUE THREAD

**Issue by dimakuv** [emilhem/graphene-erlang#1]
I suggest to add a bit more info in the README which I missed while playing with Erlang.

1. Add the tested (recommended) OS distribution. I built Erlang without any problems on my Ubuntu 18.04 by simply running `make SGX=1 DEBUG=1`. But I assume this was not tested on Ubuntu 16.04 for example.

2. I wanted to run the original (vanilla) Erlang example to understand how stuff works. By deconstructing the manifest files, I ended up with something like this:
```bash
~/graphene/Examples/graphene-erlang$ \
ROOTDIR=/home/dimakuv/graphene/Examples/graphene-erlang/install/lib/erlang \
BINDIR=/home/dimakuv/graphene/Examples/graphene-erlang/install/lib/erlang/erts-10.7/bin \
EMU=beam \
./install/lib/erlang/erts-10.7/bin/erlexec \
-noshell -s hello init -s init stop

hello, world
```

Would be nice to have it in the README.

**Comment by emilhem** [comment]
Thanks for the suggestion!

I added some information to the `README.md` now.
