### ISSUE TITLE
[strace] Analysis of vanilla execution of "hello world"

### ISSUE THREAD

**Issue by dimakuv** [emilhem/graphene-erlang#2]
Disclaimer: I have no experience with Erlang/OTP and its internal structure. Everything below is based on my strace analysis.

The analysis is based on the following strace: `ROOTDIR=/home/dimakuv/graphene/Examples/graphene-erlang/install/lib/erlang BINDIR=/home/dimakuv/graphene/Examples/graphene-erlang/install/lib/erlang/erts-10.7/bin EMU=beam strace -ff -tt -o strace ./install/lib/erlang/erts-10.7/bin/erlexec -noshell -s hello init -s init stop`

**Main process** starts as `bin/erlexec` and quickly morphs into `bin/beam.smp` via `execve()`. Then it creates 31 additional threads (on my 8-logical-cores machines):
    - 1 `sys_sig_dispatch` thread that does nothing.
    - 1 `sys_msg_dispatch` thread that does nothing.
    - 1 `async_1` thread that does nothing.
    - 8 `scheduler` threads that do `write()`, `read()`, `timerfd_settime()`, and `epoll_wait()` on non-blocking pipes `pipe([9, 10])` and `pipe([12, 13])`. They also do `madvise(MADV_FREE)` periodically.
    - 8 `dirty_cpu` threads that do nothing.
    - 10 `dirty_io` threads. Four of them do `open()`, `stat()`, and `read()` of some Erlang files, mostly bin files and logs. Other threads do nothing.
    - 1 `aux` thread that performs `ppoll(12)` and `read(12)` frequently. Apparently, this is another synchronization helper thread that listens on pipe 12 waiting for signals from `scheduler` threads.
    - 1 `poller` thread that performs `epoll_wait(4)` -- waiting on pipe end `5` and on timerfd `7`.

Interestingly, synchronization messages are simply `!` char on pipes 9/10 and 12/13. **BAD FOR GRAPHENE-SGX:** Our pipes are TLS encrypted and thus point-to-point, whereas Erlang uses MPMC on these pipes -- this breaks...

**First child process** starts as `bin/beam.smp` (after `clone()` in parent) and morths into `bin/erl_child_setup`. It reuses FDs `3` (=`19` in parent, which is one end of `socketpair([18, 19])`) from parent. It also receives FDs `6,7,8` from parent (one pipe end, one timerfd, and one epoll_fd). Then this process creates a second child process via `clone()`.

**Second child process** starts as `bin/erl_child_setup` and morths into `/bin/sh` via `execve()`. Then it morths further into Erlang's `bin/inet_gethost`. Then it creates a third and last child process via `clone()`.

**Third child process** starts as `bin/inet_gethost`. It resolves the DNS name by talking to the DNS server and reports it back to the second process via STDOUT (which was redirected by the second child process).

Surprisingly, `hello, world` is printed by one of the `scheduler` threads (in my case `8_scheduler`) of the main process.

**Comment by emilhem** [comment]
Very interesting strace analysis of Erlang/OTP!

We really appreciate the investigation that you did!

_Note that we're not developers of the Erlang/OTP, we're just doing our Master Thesis in getting Erlang/OTP to run in SGX_

Also, Erlang creates a bunch of extra threads since it expects a bigger workload than just a plain "hello world". It also has hot swapping of modules without downtime which probably creates a few extra threads that we don't use in the example. Some of these threads could be reduced by passing some options, but I don't think that it will solve the issue below:

> **BAD FOR GRAPHENE-SGX**: Our pipes are TLS encrypted and thus point-to-point, whereas Erlang uses MPMC on these pipes -- this breaks...

Interesting! I didn't know that the Graphene pipes were TLS encrypted (which is reasonable that they are). I understand why Erlang uses MPMC (Multi-Producer/Multi-Consumer) since each scheduler can produce and consume tasks.

The question is how we can get it to work with Graphene's pipes...?

> **Third child process** starts as `bin/inet_gethost`. It resolves the DNS name by talking to the DNS server and reports it back to the second process via STDOUT (which was redirected by the second child process).

Hmm, perhaps all the binaries in `bin/` should be "Graphened".

> Surprisingly, `hello, world` is printed by one of the `scheduler` threads (in my case `8_scheduler`) of the main process.

That's quite expected from Erlang since it creates a bunch of different schedulers and then throws work at them.

**Comment by dimakuv** [comment]
> I understand why Erlang uses MPMC (Multi-Producer/Multi-Consumer) since each scheduler can produce and consume tasks.
> The question is how we can get it to work with Graphene's pipes...?

Is there a way to instruct Erlang to create not normal pipes but say TCP/UDP sockets? Graphene *requires* point-to-point communications (like TCP/UDP sockets), there is no other way to have security.

> Some of these threads could be reduced by passing some options...

Could you provide me with some documentation on this? Also, I would be interested in a document with Erlang internals and architecture (of course, I can just read the official web site, but if you have a good recommendation, please share).

**Comment by emilhem** [comment]
> Is there a way to instruct Erlang to create not normal pipes but say TCP/UDP sockets? Graphene _requires_ point-to-point communications (like TCP/UDP sockets), there is no other way to have security.

I'm investigating this with the Erlang developers. This might take a while depending on their workload.

> Could you provide me with some documentation on this? Also, I would be interested in a document with Erlang internals and architecture (of course, I can just read the official web site, but if you have a good recommendation, please share).

Erlang's documentation is pretty hard to navigate.

Erlang's memory allocator options can be found here: http://erlang.org/doc/man/erts_alloc.html

Erlang's general options: http://erlang.org/doc/man/erl.html
I would suggest looking at the `+sbt` flag where you can control how Erlang binds it's schedulers to the processors/threads on the machine.

I will experiment a little more with these options, but I have to work on some attestation parts for the Master Thesis as well.

**Comment by emilhem** [comment]
No update yet from the Erlang developers.

Question: Why does Graphene make the communication on TLS tunnels? Aren't the processes/threads run in the same enclave?

**Comment by dimakuv** [comment]
> Why does Graphene make the communication on TLS tunnels? Aren't the processes/threads run in the same enclave?

There is no way for Graphene to know if an application uses pipes for inter-thread communication (intra-process communication) or for inter-process communication. So Graphene takes a conservative approach and encrypts *all* created pipes with TLS.

We *could* allow the developer to add some option in the manifest `sgx.all_pipes_are_inside_one_process` and then emulate all pipes inside the enclave. But this would require quite some work. Interestingly, Erlang is the *first* application (well, runtime engine) that uses MPMC pipes :)

**Comment by emilhem** [comment]
Interesting and reasonable!

We're out of time for this master thesis and will therefore begin working on evaluating and finishing writing the report.

Unsure whether any more work will be done from our side on making Erlang executable in Graphene.

**Comment by emilhem** [comment]
The developers responded that some of these pipes could more easily be rewritten/configurable to use TCP while other require extensive work in order to make them work with TCP. It doesn't seem business critical enough to develop these right now.

Again, thank you very much for your help! We will thank you in our paper.
